---
- name: check if snapraid is installed (changed=not)
  command: dpkg-query -W snapraid
  register: pkg_check
  failed_when: pkg_check.rc > 1
  changed_when: pkg_check.rc == 1

- name: build snapraid from source
  include: build-src.yml
  when: pkg_check.rc == 1

